version: '2'
services:
    b2share:
        image: eudatb2share/b2share:2.0.0
        environment:
            - "B2ACCESS_CONSUMER_KEY=${B2ACCESS_CONSUMER_KEY}"
            - "B2ACCESS_SECRET_KEY=${B2ACCESS_SECRET_KEY}"
            - "B2SHARE_SECRET_KEY=${B2SHARE_SECRET_KEY}"
            - "B2SHARE_JSONSCHEMAS_HOST=${B2SHARE_JSONSCHEMAS_HOST}"
            - "B2SHARE_PREFERRED_URL_SCHEME=https"
            - "B2SHARE_CACHE_REDIS_HOST='redis'"
            - "B2SHARE_CACHE_REDIS_URL='redis://redis:6379/0'"
            - "B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://redis:6379/1'"
            - "B2SHARE_BROKER_URL='amqp://guest:guest@mq:5672//'"
            - "B2SHARE_CELERY_RESULT_BACKEND='redis://redis:6379/2'"
            - "B2SHARE_SEARCH_ELASTIC_HOSTS='elasticsearch'"
        volumes:
            - "${B2SHARE_DATADIR}/b2share-data:/usr/var/b2share-instance"
        ports:
            - "5000"
        links:
            - elasticsearch
            - redis

    elasticsearch:
        build: elasticsearch
        ports:
            - "9200"
            - "9300"
        volumes:
            - "${B2SHARE_DATADIR}/elasticsearch-data:/usr/share/elasticsearch/data"

    redis:
        image: redis:3.2
        ports:
            - "6379"
        volumes:
            - "${B2SHARE_DATADIR}/redis-data:/data"

    nginx:
        build: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${B2SHARE_DATADIR}/nginx-data/ssl:/etc/ssl/"
        links:
            - b2share

    mq:
        image: rabbitmq:3.6-management
        restart: "always"
        ports:
            - "15672"
            - "5672"
        read_only: true
        volumes:
            - "${B2SHARE_DATADIR}/rabbitmq-data:/var/lib/rabbitmq"
        entrypoint:
            - "rabbitmq-server"
            - "--hostname"
            - "b2share-redis"
